# Data Types

In [1]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/user/Library/Python/3.10/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/user/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('train.csv')

In [8]:
df.head(10)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
5,5,Audi,A6 2.0T Sport,2018,40950,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,â€“,None reported,Yes,29950
6,6,Audi,A8 L 3.0T,2016,62200,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,28500
7,7,Chevrolet,Silverado 1500 1LZ,2016,102604,E85 Flex Fuel,355.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,White,Gray,None reported,Yes,12500
8,8,Ford,F-150 XLT,2020,38352,Gasoline,2.7L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Snowflake White Pearl Metallic,Black,None reported,Yes,62890
9,9,BMW,M4 Base,2015,74850,Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Blue,None reported,Yes,4000

In [9]:
df.head

<bound method NDFrame.head of             id          brand                     model  model_year  milage  \
0            0           MINI             Cooper S Base        2007  213000
1            1        Lincoln                     LS V8        2002  143250
2            2      Chevrolet         Silverado 2500 LT        2002  136731
3            3        Genesis          G90 5.0 Ultimate        2017   19500
4            4  Mercedes-Benz               Metris Base        2021    7388
...        ...            ...                       ...         ...     ...
188528  188528       Cadillac     Escalade ESV Platinum        2017   49000
188529  188529  Mercedes-Benz  AMG C 43 AMG C 43 4MATIC        2018   28600
188530  188530  Mercedes-Benz    AMG GLC 63 Base 4MATIC        2021   13650
188531  188531           Audi          S5 3.0T Prestige        2022   13895
188532  188532        Porsche                Macan Base        2016   59500

            fuel_type                                             engine  \
0            Gasoline       172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1            Gasoline       252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2       E85 Flex Fuel  320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3            Gasoline       420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4            Gasoline       208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
...               ...                                                ...
188528       Gasoline       420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
188529       Gasoline      385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
188530       Gasoline       469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
188531       Gasoline                                               3.0L
188532       Gasoline       252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel

                          transmission                    ext_col int_col  \
0                                  A/T                     Yellow    Gray
1                                  A/T                     Silver   Beige
2                                  A/T                       Blue    Gray
3       Transmission w/Dual Shift Mode                      Black   Black
4                          7-Speed A/T                      Black   Beige
...                                ...                        ...     ...
188528  Transmission w/Dual Shift Mode                      White   Beige
188529                     8-Speed A/T                      White   Black
188530                     7-Speed A/T                      White   Black
188531               1-Speed Automatic  Daytona Gray Pearl Effect   Black
188532  Transmission w/Dual Shift Mode                      White   Black

                                      accident clean_title  price
0                                None reported         Yes   4200
1       At least 1 accident or damage reported         Yes   4999
2                                None reported         Yes  13900
3                                None reported         Yes  45000
4                                None reported         Yes  97500
...                                        ...         ...    ...
188528                           None reported         Yes  27500
188529  At least 1 accident or damage reported         Yes  30000
188530                           None reported         Yes  86900
188531                           None reported         NaN  84900
188532                           None reported         Yes  28995

[188533 rows x 13 columns]>

In [10]:
df.tail

<bound method NDFrame.tail of             id          brand                     model  model_year  milage  \
0            0           MINI             Cooper S Base        2007  213000
1            1        Lincoln                     LS V8        2002  143250
2            2      Chevrolet         Silverado 2500 LT        2002  136731
3            3        Genesis          G90 5.0 Ultimate        2017   19500
4            4  Mercedes-Benz               Metris Base        2021    7388
...        ...            ...                       ...         ...     ...
188528  188528       Cadillac     Escalade ESV Platinum        2017   49000
188529  188529  Mercedes-Benz  AMG C 43 AMG C 43 4MATIC        2018   28600
188530  188530  Mercedes-Benz    AMG GLC 63 Base 4MATIC        2021   13650
188531  188531           Audi          S5 3.0T Prestige        2022   13895
188532  188532        Porsche                Macan Base        2016   59500

            fuel_type                                             engine  \
0            Gasoline       172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1            Gasoline       252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2       E85 Flex Fuel  320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3            Gasoline       420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4            Gasoline       208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
...               ...                                                ...
188528       Gasoline       420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
188529       Gasoline      385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
188530       Gasoline       469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
188531       Gasoline                                               3.0L
188532       Gasoline       252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel

                          transmission                    ext_col int_col  \
0                                  A/T                     Yellow    Gray
1                                  A/T                     Silver   Beige
2                                  A/T                       Blue    Gray
3       Transmission w/Dual Shift Mode                      Black   Black
4                          7-Speed A/T                      Black   Beige
...                                ...                        ...     ...
188528  Transmission w/Dual Shift Mode                      White   Beige
188529                     8-Speed A/T                      White   Black
188530                     7-Speed A/T                      White   Black
188531               1-Speed Automatic  Daytona Gray Pearl Effect   Black
188532  Transmission w/Dual Shift Mode                      White   Black

                                      accident clean_title  price
0                                None reported         Yes   4200
1       At least 1 accident or damage reported         Yes   4999
2                                None reported         Yes  13900
3                                None reported         Yes  45000
4                                None reported         Yes  97500
...                                        ...         ...    ...
188528                           None reported         Yes  27500
188529  At least 1 accident or damage reported         Yes  30000
188530                           None reported         Yes  86900
188531                           None reported         NaN  84900
188532                           None reported         Yes  28995

[188533 rows x 13 columns]>

In [11]:
df.info

<bound method DataFrame.info of             id          brand                     model  model_year  milage  \
0            0           MINI             Cooper S Base        2007  213000
1            1        Lincoln                     LS V8        2002  143250
2            2      Chevrolet         Silverado 2500 LT        2002  136731
3            3        Genesis          G90 5.0 Ultimate        2017   19500
4            4  Mercedes-Benz               Metris Base        2021    7388
...        ...            ...                       ...         ...     ...
188528  188528       Cadillac     Escalade ESV Platinum        2017   49000
188529  188529  Mercedes-Benz  AMG C 43 AMG C 43 4MATIC        2018   28600
188530  188530  Mercedes-Benz    AMG GLC 63 Base 4MATIC        2021   13650
188531  188531           Audi          S5 3.0T Prestige        2022   13895
188532  188532        Porsche                Macan Base        2016   59500

            fuel_type                                             engine  \
0            Gasoline       172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1            Gasoline       252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2       E85 Flex Fuel  320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3            Gasoline       420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4            Gasoline       208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
...               ...                                                ...
188528       Gasoline       420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
188529       Gasoline      385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
188530       Gasoline       469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
188531       Gasoline                                               3.0L
188532       Gasoline       252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel

                          transmission                    ext_col int_col  \
0                                  A/T                     Yellow    Gray
1                                  A/T                     Silver   Beige
2                                  A/T                       Blue    Gray
3       Transmission w/Dual Shift Mode                      Black   Black
4                          7-Speed A/T                      Black   Beige
...                                ...                        ...     ...
188528  Transmission w/Dual Shift Mode                      White   Beige
188529                     8-Speed A/T                      White   Black
188530                     7-Speed A/T                      White   Black
188531               1-Speed Automatic  Daytona Gray Pearl Effect   Black
188532  Transmission w/Dual Shift Mode                      White   Black

                                      accident clean_title  price
0                                None reported         Yes   4200
1       At least 1 accident or damage reported         Yes   4999
2                                None reported         Yes  13900
3                                None reported         Yes  45000
4                                None reported         Yes  97500
...                                        ...         ...    ...
188528                           None reported         Yes  27500
188529  At least 1 accident or damage reported         Yes  30000
188530                           None reported         Yes  86900
188531                           None reported         NaN  84900
188532                           None reported         Yes  28995

[188533 rows x 13 columns]>

# Python Exercises

In [2]:
a = 27
b = 5
print('a + b = ',a+b)
print('a - b = ',a-b)
print('a x b = ',a*b)
print('a : b = ',a/b)
print('[a : b ] = ',a//b)
print('{a : b } = ',a%b)

a + b =  32
a - b =  22
a x b =  135
a : b =  5.4
[a : b ] =  5
{a : b } =  2